### ISSUE TITLE
NPE with --offline and missing artifact

### ISSUE THREAD

**Issue by patrikbeno** [jrevolt/io.jrevolt.launcher#17]
```
 jrevolt.sh --debug --offline io.jrevolt.sysmon:io.jrevolt.sysmon.zabbix:develop-SNAPSHOT
[DBG] Using repositories:
[DBG] -      central : http://repo1.maven.org/maven2/ (<anonymous>)
[DBG] -      jrevolt : http://repo.jrevolt.io/content/groups/public/ (<anonymous>)
[ERR] Could not launch application!
[ERR] io.jrevolt.launcher.LauncherException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
[ERR] Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
[ERR] Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
[ERR] Caused by: java.lang.NullPointerException
io.jrevolt.launcher.LauncherException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at io.jrevolt.launcher.mvn.Resolver.resolveMainClassAndDependencies(Resolver.java:154)
        at io.jrevolt.launcher.mvn.Resolver.resolveAll(Resolver.java:112)
        at io.jrevolt.launcher.RepositorySupport.resolve(RepositorySupport.java:54)
        at io.jrevolt.launcher.RepositorySupport.resolve(RepositorySupport.java:28)
        at io.jrevolt.launcher.mvn.Launcher.getClassPathArchives(Launcher.java:141)
        at io.jrevolt.launcher.mvn.Launcher.getClassPathArchives(Launcher.java:70)
        at io.jrevolt.launcher.mvn.Launcher.launch(Launcher.java:94)
        at io.jrevolt.launcher.mvn.Launcher.launch(Launcher.java:150)
        at io.jrevolt.launcher.Tools.launch(Tools.java:81)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at io.jrevolt.launcher.Tools.invoke(Tools.java:53)
        at io.jrevolt.launcher.Main.launch(Main.java:81)
        at io.jrevolt.launcher.Main.main(Main.java:48)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at io.jrevolt.launcher.mvn.Resolver.resolveMainClassAndDependencies(Resolver.java:133)
        ... 21 more
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at io.jrevolt.launcher.mvn.Resolver$3.call(Resolver.java:89)
        at io.jrevolt.launcher.mvn.Resolver$3.call(Resolver.java:86)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ... 1 more
Caused by: java.lang.NullPointerException
        at io.jrevolt.launcher.mvn.RepositoryConnector.download(RepositoryConnector.java:330)
        at io.jrevolt.launcher.mvn.RepositoryConnector.resolveSnapshotVersion(RepositoryConnector.java:445)
        at io.jrevolt.launcher.mvn.RepositoryConnector.resolve(RepositoryConnector.java:187)
        at io.jrevolt.launcher.mvn.Resolver$2.call(Resolver.java:76)
        at io.jrevolt.launcher.mvn.Resolver$2.call(Resolver.java:73)
        ... 4 more
```

**Comment by patrikbeno** [comment]
Seems fixed as part of #13
